id: P010464
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:51:13.700234
source_metadata:
  id: bdr:W1KG9676
  title: ཀུན་རིག་རོ་བསྲེག་གི་ཆོ་ག་སྲིད་པའི་ཆུ་ཀླུང་སྐེམས་པའི་ཡེ་ཤེས་སྣང་བྱེད་ནོར་བུ་སོགས།
  author: ''
  volumes:
    712baf192a7745899f81c88ebfcf7820:
      image_group_id: I1KG9696
      title: ''
      volume_number: 1
      total_pages: 568
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
